/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto_programación_ii;

import java.awt.BorderLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Oswal Fuentes
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        this.setUndecorated(true);
        this.setResizable(false);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int ancho = (int) tk.getScreenSize().getWidth();
        int alto = (int) tk.getScreenSize().getHeight();
        this.setSize(ancho, alto);
        jd_login.setUndecorated(true);
        jd_login.setModal(true);//Bloquear otras ventanas
        jd_login.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_login.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_login.setResizable(false);//No se puede modificar el tamaño
        jd_login.setVisible(true);
        Height = (int) jp_principal.getSize().getHeight();
        Width = (int) jp_principal.getSize().getWidth();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jd_login = new javax.swing.JDialog();
        lb_foto = new javax.swing.JLabel();
        tf_pass = new javax.swing.JPasswordField();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton20 = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        cb_correos = new javax.swing.JComboBox<>();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jd_redactar = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        cb_contactos = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        tf_asunto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_cuerpo = new javax.swing.JTextArea();
        jButton17 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jd_crear_cuenta = new javax.swing.JDialog();
        jlb_foto = new javax.swing.JLabel();
        tf_nombre = new javax.swing.JTextField();
        tf_correo = new javax.swing.JTextField();
        tf_telefono = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButton18 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        cb_genero = new javax.swing.JComboBox<>();
        jButton19 = new javax.swing.JButton();
        dc_fecha_nacimiento = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        pf_contraseña = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jd_config = new javax.swing.JDialog();
        jlb_foto_config = new javax.swing.JLabel();
        tf_nombre_config = new javax.swing.JTextField();
        tf_correo_config = new javax.swing.JTextField();
        tf_telefono_config = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton27 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        cb_genero_config = new javax.swing.JComboBox<>();
        jButton28 = new javax.swing.JButton();
        dc_fecha_nacimiento_config = new com.toedter.calendar.JDateChooser();
        jLabel29 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        tf_contraseña_config = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jp_principal = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jd_login.setTitle("Login");

        lb_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setText("Acceder");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });

        jLabel1.setText("Correo");

        jLabel2.setText("Contraseña");

        jButton20.setText("Crear cuenta");
        jButton20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton20MouseClicked(evt);
            }
        });

        jLabel19.setText("¿No tienes cuenta?");

        cb_correos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_correosItemStateChanged(evt);
            }
        });

        jButton21.setText("Actualizar");
        jButton21.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton21MouseClicked(evt);
            }
        });

        jButton22.setText("Cerrar");
        jButton22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton22MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_loginLayout = new javax.swing.GroupLayout(jd_login.getContentPane());
        jd_login.getContentPane().setLayout(jd_loginLayout);
        jd_loginLayout.setHorizontalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_loginLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton22)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20))
                    .addGroup(jd_loginLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cb_correos, 0, 200, Short.MAX_VALUE)
                            .addComponent(tf_pass)
                            .addGroup(jd_loginLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton21)))
                .addContainerGap())
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_loginLayout.setVerticalGroup(
            jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_loginLayout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addComponent(lb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cb_correos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton21)))
                .addGap(18, 18, 18)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jd_loginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton20)
                    .addComponent(jLabel19)
                    .addComponent(jButton22))
                .addContainerGap())
        );

        jd_redactar.setTitle("Redactar correo");

        jLabel10.setText("Para");

        jLabel11.setText("Asunto");

        ta_cuerpo.setColumns(20);
        ta_cuerpo.setRows(5);
        jScrollPane1.setViewportView(ta_cuerpo);

        jButton17.setText("Enviar");
        jButton17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton17MouseClicked(evt);
            }
        });

        jButton11.setText("Actualizar lista");
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton11MouseClicked(evt);
            }
        });

        jButton12.setText("Adjuntar archivo");
        jButton12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton12MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_redactarLayout = new javax.swing.GroupLayout(jd_redactar.getContentPane());
        jd_redactar.getContentPane().setLayout(jd_redactarLayout);
        jd_redactarLayout.setHorizontalGroup(
            jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_redactarLayout.createSequentialGroup()
                .addGroup(jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_redactarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
                    .addGroup(jd_redactarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton17))
                    .addGroup(jd_redactarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_asunto)
                            .addComponent(cb_contactos, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton11)))
                .addContainerGap())
        );
        jd_redactarLayout.setVerticalGroup(
            jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_redactarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cb_contactos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton11))
                .addGap(18, 18, 18)
                .addGroup(jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jd_redactarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton17)
                    .addComponent(jButton12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );

        jd_crear_cuenta.setTitle("Crear cuenta");

        jlb_foto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel13.setText("Nombre");

        jLabel14.setText("Usuario");

        jLabel15.setText("Telefono");

        jLabel16.setText("Fecha de nacimiento");

        jLabel17.setText("Genero");

        jButton18.setText("Seleccionar");
        jButton18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton18MouseClicked(evt);
            }
        });

        jLabel18.setText("Foto");

        cb_genero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jButton19.setText("Crear cuenta");
        jButton19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton19MouseClicked(evt);
            }
        });

        jLabel20.setText("Contraseña");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("@minigmail.edu");

        javax.swing.GroupLayout jd_crear_cuentaLayout = new javax.swing.GroupLayout(jd_crear_cuenta.getContentPane());
        jd_crear_cuenta.getContentPane().setLayout(jd_crear_cuentaLayout);
        jd_crear_cuentaLayout.setHorizontalGroup(
            jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_crear_cuentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                        .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_telefono)
                            .addComponent(dc_fecha_nacimiento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pf_contraseña)
                            .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                                .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))
                            .addComponent(tf_nombre))
                        .addGap(110, 110, 110))
                    .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                        .addComponent(jlb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jButton18))
                            .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLabel18)))
                        .addGap(95, 95, 95))))
        );
        jd_crear_cuentaLayout.setVerticalGroup(
            jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlb_foto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_crear_cuentaLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton18)))
                .addGap(41, 41, 41)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf_correo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(pf_contraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(tf_telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16)
                    .addComponent(dc_fecha_nacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_crear_cuentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cb_genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton19, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
        );

        jd_config.setTitle("Configuraciones");

        jlb_foto_config.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Nombre");

        jLabel24.setText("Correo");

        jLabel25.setText("Telefono");

        jLabel26.setText("Fecha de nacimiento");

        jLabel27.setText("Genero");

        jButton27.setText("Seleccionar");
        jButton27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton27MouseClicked(evt);
            }
        });

        jLabel28.setText("Foto");

        cb_genero_config.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));

        jButton28.setText("Guardar cambios");
        jButton28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton28MouseClicked(evt);
            }
        });

        jLabel29.setText("Contraseña");

        jButton10.setText("Eliminar correo");
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jd_configLayout = new javax.swing.GroupLayout(jd_config.getContentPane());
        jd_config.getContentPane().setLayout(jd_configLayout);
        jd_configLayout.setHorizontalGroup(
            jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_configLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_configLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_configLayout.createSequentialGroup()
                        .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel29, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf_correo_config)
                            .addComponent(tf_telefono_config)
                            .addComponent(dc_fecha_nacimiento_config, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                            .addComponent(cb_genero_config, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tf_contraseña_config))
                        .addGap(110, 110, 110))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_configLayout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(18, 18, 18)
                        .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_configLayout.createSequentialGroup()
                                .addComponent(jlb_foto_config, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_configLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton27))
                                    .addGroup(jd_configLayout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel28))))
                            .addComponent(tf_nombre_config, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_configLayout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addContainerGap())))
        );
        jd_configLayout.setVerticalGroup(
            jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_configLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jlb_foto_config, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jd_configLayout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton27)))
                .addGap(41, 41, 41)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_nombre_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(tf_correo_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(tf_contraseña_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(tf_telefono_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel26)
                    .addComponent(dc_fecha_nacimiento_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jd_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cb_genero_config, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(jButton28, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jButton10)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Redactar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Recibidos");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("Enviados");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("SPAM");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("Papelera");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jp_principalLayout = new javax.swing.GroupLayout(jp_principal);
        jp_principal.setLayout(jp_principalLayout);
        jp_principalLayout.setHorizontalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 684, Short.MAX_VALUE)
        );
        jp_principalLayout.setVerticalGroup(
            jp_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton7.setText("Cerrar sesión");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Borradores");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        jButton9.setText("Configuraciones");
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jp_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jp_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        Correo temp2 = (Correo) cb_correos.getSelectedItem();
        if (tf_pass.getText().equals(temp2.getContraseña())) {
            JOptionPane.showMessageDialog(this, "Ha ingresado!");
            jd_login.dispose();
            this.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Correo/Contraseña incorrectos");
        }
    }//GEN-LAST:event_jButton6MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        panel_recibidos p1 = new panel_recibidos();
        p1.setSize(Width, Height);
        p1.setLocation(0, 0);
        jp_principal.removeAll();
        jp_principal.add(p1, BorderLayout.CENTER);
        jp_principal.revalidate();
        jp_principal.repaint();
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        panel_recibidos pr = new panel_recibidos();
        pr.traerTable().setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "Clase", "UV"
                }
        ));
        int pos = 0;
        for (Correo_E t : ap.getListaCorreos().get(cb_correos.getSelectedIndex()).getCorreos_E()) {
            if (ap.getListaCorreos().get(cb_correos.getSelectedIndex()).getCorreos_E().get(pos).getBandeja().equals("Recibidos")) {
                Object row[] = {t.getAsunto(), t.getRemitente()};
                DefaultTableModel m = (DefaultTableModel) pr.traerTable().getModel();
                m.addRow(row);
                pr.traerTable().setModel(m);
            }
        }
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        panel_enviados p2 = new panel_enviados();
        p2.setSize(Width, Height);
        p2.setLocation(0, 0);
        jp_principal.removeAll();
        jp_principal.add(p2, BorderLayout.CENTER);
        jp_principal.revalidate();
        jp_principal.repaint();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        panel_spam p3 = new panel_spam();
        p3.setSize(Width, Height);
        p3.setLocation(0, 0);
        jp_principal.removeAll();
        jp_principal.add(p3, BorderLayout.CENTER);
        jp_principal.revalidate();
        jp_principal.repaint();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        panel_borradores p4 = new panel_borradores();
        p4.setSize(Width, Height);
        p4.setLocation(0, 0);
        jp_principal.removeAll();
        jp_principal.add(p4, BorderLayout.CENTER);
        jp_principal.revalidate();
        jp_principal.repaint();
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        panel_papelera p5 = new panel_papelera();
        p5.setSize(Width, Height);
        p5.setLocation(0, 0);
        jp_principal.removeAll();
        jp_principal.add(p5, BorderLayout.CENTER);
        jp_principal.revalidate();
        jp_principal.repaint();
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseClicked
        int pos = cb_correos.getSelectedIndex();
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        jlb_foto_config.setIcon(ap.getListaCorreos().get(pos).getFoto());
        tf_nombre_config.setText(ap.getListaCorreos().get(pos).getNombre());
        tf_correo_config.setText(ap.getListaCorreos().get(pos).getCorreo());
        tf_contraseña_config.setText(ap.getListaCorreos().get(pos).getContraseña());
        tf_telefono_config.setText(ap.getListaCorreos().get(pos).getTelefono());
        dc_fecha_nacimiento_config.setDate(ap.getListaCorreos().get(pos).getFecha_nacimiento());
        cb_genero_config.setSelectedItem(ap.getListaCorreos().get(pos).getGenero());
        jd_config.setModal(true);//Bloquear otras ventanas
        jd_config.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_config.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_config.setResizable(false);//No se puede modificar el tamaño
        jd_config.setVisible(true);
    }//GEN-LAST:event_jButton9MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        jd_redactar.setModal(true);//Bloquear otras ventanas
        jd_redactar.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_redactar.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_redactar.setResizable(false);//No se puede modificar el tamaño
        jd_redactar.setVisible(true);
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        Correo_E c = new Correo_E(tf_asunto.getText(), ta_cuerpo.getText(), "Borradores", null, null);
        ap.getListaCorreos().get(cb_correos.getSelectedIndex()).setCorreo_E(c);
        ap.escribirArchivo();
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton20MouseClicked
        jd_crear_cuenta.setModal(true);//Bloquear otras ventanas
        jd_crear_cuenta.pack();//Acoplar el tamaño a la ventana a los elementos que incluye
        jd_crear_cuenta.setLocationRelativeTo(this);//Ubicar la ventana en una posicion
        jd_crear_cuenta.setResizable(false);//No se puede modificar el tamaño
        jd_crear_cuenta.setVisible(true);
    }//GEN-LAST:event_jButton20MouseClicked

    private void jButton19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton19MouseClicked
        Correo c = new Correo(tf_nombre.getText(), tf_correo.getText() + "@minigmail.edu", pf_contraseña.getText(), tf_telefono.getText(),
                (String) cb_genero.getSelectedItem(), dc_fecha_nacimiento.getDate(), jlb_foto.getIcon());
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        ap.setCorreo(c);
        ap.escribirArchivo();
        JOptionPane.showMessageDialog(this, "Correo creado exitosamente!");
        jd_crear_cuenta.dispose();
        tf_nombre.setText("");
        tf_correo.setText("");
        pf_contraseña.setText("");
        tf_telefono.setText("");
        cb_genero.setSelectedItem(null);
        dc_fecha_nacimiento.setDate(null);
        jlb_foto.setIcon(null);
    }//GEN-LAST:event_jButton19MouseClicked

    private void jButton18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton18MouseClicked
        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.jlb_foto.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton18MouseClicked

    private void jButton21MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton21MouseClicked
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListaCorreos().toArray());
        cb_correos.setModel(modelo);
    }//GEN-LAST:event_jButton21MouseClicked

    private void cb_correosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_correosItemStateChanged
        Correo temp = (Correo) cb_correos.getSelectedItem();
        lb_foto.setIcon(temp.getFoto());
    }//GEN-LAST:event_cb_correosItemStateChanged

    private void jButton22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton22MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jButton22MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (evt.getSource() == jButton7) {
            dispose();
            Principal restart = new Principal();
            restart.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton27MouseClicked
        JFileChooser fc = new JFileChooser();
        FileFilter filtro = new FileNameExtensionFilter("Imagenes", "png", "jpg", "jpeg", "gif");
        fc.setFileFilter(filtro);
        File archivo;
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            archivo = fc.getSelectedFile();
            Image img = Toolkit.getDefaultToolkit().createImage(archivo.getPath()).getScaledInstance(100, 100, 0);
            this.jlb_foto_config.setIcon(new ImageIcon(img));
        }
    }//GEN-LAST:event_jButton27MouseClicked

    private void jButton28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton28MouseClicked
        int pos = cb_correos.getSelectedIndex();
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        ap.getListaCorreos().get(pos).setFoto(jlb_foto_config.getIcon());
        ap.getListaCorreos().get(pos).setNombre(tf_nombre_config.getText());
        ap.getListaCorreos().get(pos).setCorreo(tf_correo_config.getText());
        ap.getListaCorreos().get(pos).setContraseña(tf_contraseña_config.getText());
        ap.getListaCorreos().get(pos).setTelefono(tf_telefono_config.getText());
        ap.getListaCorreos().get(pos).setFecha_nacimiento(dc_fecha_nacimiento_config.getDate());
        ap.getListaCorreos().get(pos).setGenero((String) cb_genero_config.getSelectedItem());
        ap.escribirArchivo();
        jd_config.dispose();
        JOptionPane.showMessageDialog(this, "Se ha modificado la cuenta exitosamente");
    }//GEN-LAST:event_jButton28MouseClicked

    private void jButton10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseClicked
        String resp = JOptionPane.showInputDialog("¿Esta seguro que desea eliminar su cuenta de correo electronico? [s/n]");
        if (resp.equals("s") || resp.equals("S")) {
            int pos = cb_correos.getSelectedIndex();
            adminCorreo ap = new adminCorreo("./correos.cbm");
            ap.cargarArchivo();
            ap.getListaCorreos().remove(pos);
            ap.escribirArchivo();
            jd_config.dispose();
        }
        if (evt.getSource() == jButton10) {
            dispose();
            Principal restart = new Principal();
            restart.setVisible(true);
        }
    }//GEN-LAST:event_jButton10MouseClicked

    private void jButton11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseClicked
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        DefaultComboBoxModel modelo = new DefaultComboBoxModel(ap.getListaCorreos().toArray());
        cb_contactos.setModel(modelo);
    }//GEN-LAST:event_jButton11MouseClicked

    private void jButton12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton12MouseClicked
        JFileChooser fc = new JFileChooser();
        int op = fc.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            adminCorreo ap = new adminCorreo("./correos.cbm");
            ap.cargarArchivo();
            int tam = ap.getListaCorreos().get(cb_correos.getSelectedIndex()).getCorreos_E().size() - 1;
            ap.getListaCorreos().get(cb_correos.getSelectedIndex()).getCorreos_E().get(tam).setArchivo(fc.getSelectedFile());
            JOptionPane.showMessageDialog(this, "Se adjunto el archivo exitosamente");
        }
    }//GEN-LAST:event_jButton12MouseClicked

    private void jButton17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton17MouseClicked
        /*
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        Correo_E c = new Correo_E(tf_asunto.getText(), ta_cuerpo.getText(), "Borradores", ap.getListaCorreos().get(cb_contactos.getSelectedIndex()));
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).setCorreo_E(c);
        ap.escribirArchivo();
         */
        adminCorreo ap = new adminCorreo("./correos.cbm");
        ap.cargarArchivo();
        int tam = ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).getCorreos_E().size() - 1;
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).getCorreos_E().get(tam).setAsunto(tf_asunto.getText());
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).getCorreos_E().get(tam).setBandeja("Enviados");
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).getCorreos_E().get(tam).setCuerpo(ta_cuerpo.getText());
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).getCorreos_E().get(tam).setDestinatario((Correo) cb_contactos.getSelectedItem());
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).getCorreos_E().get(tam).setRemitente((Correo) cb_correos.getSelectedItem());
        //asignar en bandeja de entrada de el destinatario
        Correo_E c = new Correo_E(tf_asunto.getText(), ta_cuerpo.getText(), "Recibidos", ap.getListaCorreos().
                get(cb_contactos.getSelectedIndex()), ap.getListaCorreos().get(cb_correos.getSelectedIndex()));
        ap.getListaCorreos().get(cb_contactos.getSelectedIndex()).setCorreo_E(c);
        JOptionPane.showMessageDialog(this, "Se ha enviado el correo");
        tf_asunto.setText("");
        ta_cuerpo.setText("");
        cb_contactos.setSelectedIndex(0);
    }//GEN-LAST:event_jButton17MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cb_contactos;
    private javax.swing.JComboBox<String> cb_correos;
    private javax.swing.JComboBox<String> cb_genero;
    private javax.swing.JComboBox<String> cb_genero_config;
    private com.toedter.calendar.JDateChooser dc_fecha_nacimiento;
    private com.toedter.calendar.JDateChooser dc_fecha_nacimiento_config;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton27;
    private javax.swing.JButton jButton28;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JDialog jd_config;
    private javax.swing.JDialog jd_crear_cuenta;
    private javax.swing.JDialog jd_login;
    private javax.swing.JDialog jd_redactar;
    private javax.swing.JLabel jlb_foto;
    private javax.swing.JLabel jlb_foto_config;
    private javax.swing.JPanel jp_principal;
    private javax.swing.JLabel lb_foto;
    private javax.swing.JPasswordField pf_contraseña;
    private javax.swing.JTextArea ta_cuerpo;
    private javax.swing.JTextField tf_asunto;
    private javax.swing.JTextField tf_contraseña_config;
    private javax.swing.JTextField tf_correo;
    private javax.swing.JTextField tf_correo_config;
    private javax.swing.JTextField tf_nombre;
    private javax.swing.JTextField tf_nombre_config;
    private javax.swing.JPasswordField tf_pass;
    private javax.swing.JTextField tf_telefono;
    private javax.swing.JTextField tf_telefono_config;
    // End of variables declaration//GEN-END:variables
    int Height = 0, Width = 0;
}
